var namespacesophus =
[
    [ "detail", "namespacesophus_1_1detail.html", "namespacesophus_1_1detail" ],
    [ "jet_helpers", "namespacesophus_1_1jet__helpers.html", "namespacesophus_1_1jet__helpers" ],
    [ "AffineTransform", "classsophus_1_1_affine_transform.html", "classsophus_1_1_affine_transform" ],
    [ "AnyImagePredicate", "structsophus_1_1_any_image_predicate.html", null ],
    [ "BasisSpline", "classsophus_1_1_basis_spline.html", "classsophus_1_1_basis_spline" ],
    [ "BasisSplineFn", "classsophus_1_1_basis_spline_fn.html", "classsophus_1_1_basis_spline_fn" ],
    [ "BasisSplineImpl", "classsophus_1_1_basis_spline_impl.html", "classsophus_1_1_basis_spline_impl" ],
    [ "BasisSplineSegment", "structsophus_1_1_basis_spline_segment.html", "structsophus_1_1_basis_spline_segment" ],
    [ "BrownConradyTransform", "classsophus_1_1_brown_conrady_transform.html", "classsophus_1_1_brown_conrady_transform" ],
    [ "CameraInRig", "structsophus_1_1_camera_in_rig.html", "structsophus_1_1_camera_in_rig" ],
    [ "CameraModel", "classsophus_1_1_camera_model.html", "classsophus_1_1_camera_model" ],
    [ "CameraModelT", "classsophus_1_1_camera_model_t.html", "classsophus_1_1_camera_model_t" ],
    [ "Cartesian", "classsophus_1_1_cartesian.html", "classsophus_1_1_cartesian" ],
    [ "CartesianBase", "classsophus_1_1_cartesian_base.html", "classsophus_1_1_cartesian_base" ],
    [ "ClippingPlanes", "structsophus_1_1_clipping_planes.html", "structsophus_1_1_clipping_planes" ],
    [ "ClosestApproachResult", "structsophus_1_1_closest_approach_result.html", "structsophus_1_1_closest_approach_result" ],
    [ "GetScalar", "structsophus_1_1_get_scalar.html", "structsophus_1_1_get_scalar" ],
    [ "GetScalar< Eigen::Matrix< TScalar, kM, kMatrixDim > >", "structsophus_1_1_get_scalar_3_01_eigen_1_1_matrix_3_01_t_scalar_00_01k_m_00_01k_matrix_dim_01_4_01_4.html", "structsophus_1_1_get_scalar_3_01_eigen_1_1_matrix_3_01_t_scalar_00_01k_m_00_01k_matrix_dim_01_4_01_4" ],
    [ "Image", "classsophus_1_1_image.html", "classsophus_1_1_image" ],
    [ "ImageShape", "classsophus_1_1_image_shape.html", "classsophus_1_1_image_shape" ],
    [ "ImageSize", "structsophus_1_1_image_size.html", "structsophus_1_1_image_size" ],
    [ "ImageTraits", "structsophus_1_1_image_traits.html", "structsophus_1_1_image_traits" ],
    [ "ImageTraits< Eigen::Matrix< TT, kNumChannelsT, 1 > >", "structsophus_1_1_image_traits_3_01_eigen_1_1_matrix_3_01_t_t_00_01k_num_channels_t_00_011_01_4_01_4.html", "structsophus_1_1_image_traits_3_01_eigen_1_1_matrix_3_01_t_t_00_01k_num_channels_t_00_011_01_4_01_4" ],
    [ "ImuModel", "classsophus_1_1_imu_model.html", "classsophus_1_1_imu_model" ],
    [ "IndexAndU", "structsophus_1_1_index_and_u.html", "structsophus_1_1_index_and_u" ],
    [ "InverseDepthPoint3", "classsophus_1_1_inverse_depth_point3.html", "classsophus_1_1_inverse_depth_point3" ],
    [ "IsFixedSizeVector", "structsophus_1_1_is_fixed_size_vector.html", null ],
    [ "IsFloatingPoint", "structsophus_1_1_is_floating_point.html", null ],
    [ "IsFloatingPoint< Eigen::Matrix< TScalar, kM, kMatrixDim > >", "structsophus_1_1_is_floating_point_3_01_eigen_1_1_matrix_3_01_t_scalar_00_01k_m_00_01k_matrix_dim_01_4_01_4.html", null ],
    [ "IsUniformRandomBitGenerator", "structsophus_1_1_is_uniform_random_bit_generator.html", null ],
    [ "KannalaBrandtK3Transform", "classsophus_1_1_kannala_brandt_k3_transform.html", "classsophus_1_1_kannala_brandt_k3_transform" ],
    [ "LieGroupCeresTests", "structsophus_1_1_lie_group_ceres_tests.html", "structsophus_1_1_lie_group_ceres_tests" ],
    [ "LieGroupTests", "classsophus_1_1_lie_group_tests.html", "classsophus_1_1_lie_group_tests" ],
    [ "Manifold", "classsophus_1_1_manifold.html", "classsophus_1_1_manifold" ],
    [ "Mapper", "structsophus_1_1_mapper.html", "structsophus_1_1_mapper" ],
    [ "Mapper< TScalar, typename std::enable_if< kIsMappableV< TScalar > >::type >", "structsophus_1_1_mapper_3_01_t_scalar_00_01typename_01std_1_1enable__if_3_01k_is_mappable_v_3_01cd5529748b13d40e64d4c3ee260777da.html", "structsophus_1_1_mapper_3_01_t_scalar_00_01typename_01std_1_1enable__if_3_01k_is_mappable_v_3_01cd5529748b13d40e64d4c3ee260777da" ],
    [ "MaybeLeakingUniqueDataAreaDeleter", "structsophus_1_1_maybe_leaking_unique_data_area_deleter.html", "structsophus_1_1_maybe_leaking_unique_data_area_deleter" ],
    [ "MultiCameraRig", "structsophus_1_1_multi_camera_rig.html", "structsophus_1_1_multi_camera_rig" ],
    [ "MutImage", "classsophus_1_1_mut_image.html", "classsophus_1_1_mut_image" ],
    [ "MutImageView", "classsophus_1_1_mut_image_view.html", "classsophus_1_1_mut_image_view" ],
    [ "MutRuntimeImage", "classsophus_1_1_mut_runtime_image.html", "classsophus_1_1_mut_runtime_image" ],
    [ "MutRuntimeImageView", "classsophus_1_1_mut_runtime_image_view.html", "classsophus_1_1_mut_runtime_image_view" ],
    [ "PointTraits", "structsophus_1_1_point_traits.html", null ],
    [ "PointTraits< TPoint >", "structsophus_1_1_point_traits_3_01_t_point_01_4.html", "structsophus_1_1_point_traits_3_01_t_point_01_4" ],
    [ "PointTransformer", "classsophus_1_1_point_transformer.html", "classsophus_1_1_point_transformer" ],
    [ "ProjectionOrtho", "structsophus_1_1_projection_ortho.html", "structsophus_1_1_projection_ortho" ],
    [ "ProjectionZ1", "structsophus_1_1_projection_z1.html", "structsophus_1_1_projection_z1" ],
    [ "Random", "structsophus_1_1_random.html", null ],
    [ "Random< double >", "structsophus_1_1_random_3_01double_01_4.html", "structsophus_1_1_random_3_01double_01_4" ],
    [ "Ray", "classsophus_1_1_ray.html", "classsophus_1_1_ray" ],
    [ "Region", "classsophus_1_1_region.html", "classsophus_1_1_region" ],
    [ "RuntimeImage", "classsophus_1_1_runtime_image.html", "classsophus_1_1_runtime_image" ],
    [ "RuntimeImageView", "classsophus_1_1_runtime_image_view.html", "classsophus_1_1_runtime_image_view" ],
    [ "RuntimePixelType", "structsophus_1_1_runtime_pixel_type.html", "structsophus_1_1_runtime_pixel_type" ],
    [ "RxSo2", "classsophus_1_1_rx_so2.html", "classsophus_1_1_rx_so2" ],
    [ "RxSo2Base", "classsophus_1_1_rx_so2_base.html", "classsophus_1_1_rx_so2_base" ],
    [ "RxSo3", "classsophus_1_1_rx_so3.html", "classsophus_1_1_rx_so3" ],
    [ "RxSo3Base", "classsophus_1_1_rx_so3_base.html", "classsophus_1_1_rx_so3_base" ],
    [ "ScalingNonOrthogonalityAcceleroModel", "structsophus_1_1_scaling_non_orthogonality_accelero_model.html", "structsophus_1_1_scaling_non_orthogonality_accelero_model" ],
    [ "ScalingNonOrthogonalityGyroModel", "structsophus_1_1_scaling_non_orthogonality_gyro_model.html", "structsophus_1_1_scaling_non_orthogonality_gyro_model" ],
    [ "Se2", "classsophus_1_1_se2.html", "classsophus_1_1_se2" ],
    [ "Se2Base", "classsophus_1_1_se2_base.html", "classsophus_1_1_se2_base" ],
    [ "Se3", "classsophus_1_1_se3.html", "classsophus_1_1_se3" ],
    [ "Se3Base", "classsophus_1_1_se3_base.html", "classsophus_1_1_se3_base" ],
    [ "Sim2", "classsophus_1_1_sim2.html", "classsophus_1_1_sim2" ],
    [ "Sim2Base", "classsophus_1_1_sim2_base.html", "classsophus_1_1_sim2_base" ],
    [ "Sim3", "classsophus_1_1_sim3.html", "classsophus_1_1_sim3" ],
    [ "Sim3Base", "classsophus_1_1_sim3_base.html", "classsophus_1_1_sim3_base" ],
    [ "So2", "classsophus_1_1_so2.html", "classsophus_1_1_so2" ],
    [ "So2Base", "classsophus_1_1_so2_base.html", "classsophus_1_1_so2_base" ],
    [ "So3", "classsophus_1_1_so3.html", "classsophus_1_1_so3" ],
    [ "So3Base", "classsophus_1_1_so3_base.html", "classsophus_1_1_so3_base" ],
    [ "SplineBasisFunction", "classsophus_1_1_spline_basis_function.html", null ],
    [ "Tests", "classsophus_1_1_tests.html", "classsophus_1_1_tests" ],
    [ "UninitTag", "structsophus_1_1_uninit_tag.html", null ],
    [ "UniqueDataAreaDeleter", "structsophus_1_1_unique_data_area_deleter.html", "structsophus_1_1_unique_data_area_deleter" ],
    [ "UnitVector", "classsophus_1_1_unit_vector.html", "classsophus_1_1_unit_vector" ],
    [ "VariantImagePredicate", "structsophus_1_1_variant_image_predicate.html", "structsophus_1_1_variant_image_predicate" ]
];